project_id: &id001
- GCF-2023-901
organism: metagenome
filter:
  subsample_fastq: skip
libprepkit: Illumina Nextera XT DNA Library Prep
read_geometry:
- 151
- 151
machine: MiSeq StOlav
experiment_principal_inverstigator: NA
experiment_title: *id001
experiment_summary: NA
quant:
  batch:
    method: skip
fastq_dir: data/raw/fastq
descriptors:
  Organism:
    display_name: Organism
    dtype: string
    subtype: organism
    description: organism name (genus_species)
    placement: 6
  Flowcell_ID:
    display_name: Flowcell ID
    description: flowcell id tag
    dtype: categorical
    placement: 36
    subtype: constant
  Project_ID:
    display_name: GCF Project ID
    dtype: string
    subtype: gcf_number
    description: GCF project ID. (GCF-year-number)
    placement: 4
  Flowcell_Name:
    display_name: Flowcell Name
    description: flowcell folder name
    dtype: string
    subtype: no_conversion
    placement: 35
  R1:
    display_name: Read 1
    dtype: path
    description: ' read 1 fastq filename'
    placement: 1000
  Sample_ID:
    display_name: Sample ID
    dtype: string
    subtype: no_conversion
    description: unique sample id
    placement: 0
  R2:
    display_name: Read 2
    dtype: path
    description: read 2 fastq filename
    placement: 1001
samples:
  Bact:
    Sample_ID: Bact
    Project_ID: GCF-2023-901
    Organism: pteropus_vampyrus
    Flowcell_Name: 231002_M03942_0070_000000000-L83M5
    Flowcell_ID: 000000000-L83M5
    R1: 231002_M03942_0070_000000000-L83M5/GCF-2023-901/Bact_R1.fastq.gz
    R2: 231002_M03942_0070_000000000-L83M5/GCF-2023-901/Bact_R2.fastq.gz
  Yeast:
    Sample_ID: Yeast
    Project_ID: GCF-2023-901
    Organism: saccharomyces_cerevisiae
    Flowcell_Name: 231002_M03942_0070_000000000-L83M5
    Flowcell_ID: 000000000-L83M5
    R1: 231002_M03942_0070_000000000-L83M5/GCF-2023-901/Yeast_R1.fastq.gz
    R2: 231002_M03942_0070_000000000-L83M5/GCF-2023-901/Yeast_R2.fastq.gz
db:
  reference_db: langmead
workflow: metagenome
libprep_name: Illumina_Nextera_XT_DNA_Library_Prep2_PE
library_source: genomic
library_strategy: WGS
library_selection: RANDOM
library_strand: first strand
read_orientation: unstranded
delta_readlen:
- 0
- 0
adapter: CTGTCTCTTATACACATCT
adapter2: CTGTCTCTTATACACATCT
protocol:
  library_construction: ''
  sequencing: ''
