project_id:
- GCF-2020-746
organism: homo_sapiens
libprepkit: Custom
read_geometry:
- 151
- 151
machine: NextSeq 500
quant:
  batch:
    method: skip
fastq_dir: data/raw/fastq
samples:
  B31:
    R1: 210519_NB501038_0285_AHC3THBGXJ/GCF-2020-746/B31_R1.fastq.gz
    R2: 210519_NB501038_0285_AHC3THBGXJ/GCF-2020-746/B31_R2.fastq.gz
    paired_end: 1
    Sample_ID: B31
    External_ID: ''
    Project_ID: GCF-2020-746
    Organism: Human
    Sample_Biosource: FFPE tumor tissue
    Index1_p7 (If dual indexed libraries are submitted indicate what index sequence is used P7): 704
    Index2_p5 (If libraries are submitted  indicate what index sequence is used P75): 510
    Sample_Group: ''
    Customer_Comment: ''
    Project ID: GCF-2020-746
    RIN: ''
    SpikeIn: ''
    Fragment_Length: ''
    Fragment_SD: ''
    Concentration: ''
    260/280: ''
    260/230: ''
    Lab_Comment: ''
  B61:
    R1: 210519_NB501038_0285_AHC3THBGXJ/GCF-2020-746/B61_R1.fastq.gz
    R2: 210519_NB501038_0285_AHC3THBGXJ/GCF-2020-746/B61_R2.fastq.gz
    paired_end: 1
    Sample_ID: B61
    External_ID: ''
    Project_ID: GCF-2020-746
    Organism: Human
    Sample_Biosource: Whole blood
    Index1_p7 (If dual indexed libraries are submitted indicate what index sequence is used P7): 711
    Index2_p5 (If libraries are submitted  indicate what index sequence is used P75): 505
    Sample_Group: ''
    Customer_Comment: ''
    Project ID: GCF-2020-746
    RIN: ''
    SpikeIn: ''
    Fragment_Length: ''
    Fragment_SD: ''
    Concentration: ''
    260/280: ''
    260/230: ''
    Lab_Comment: ''
  B78:
    R1: 210519_NB501038_0285_AHC3THBGXJ/GCF-2020-746/B78_R1.fastq.gz
    R2: 210519_NB501038_0285_AHC3THBGXJ/GCF-2020-746/B78_R2.fastq.gz
    paired_end: 1
    Sample_ID: B78
    External_ID: ''
    Project_ID: GCF-2020-746
    Organism: Human
    Sample_Biosource: Whole blood
    Index1_p7 (If dual indexed libraries are submitted indicate what index sequence is used P7): 714
    Index2_p5 (If libraries are submitted  indicate what index sequence is used P75): 506
    Sample_Group: ''
    Customer_Comment: ''
    Project ID: GCF-2020-746
    RIN: ''
    SpikeIn: ''
    Fragment_Length: ''
    Fragment_SD: ''
    Concentration: ''
    260/280: ''
    260/230: ''
    Lab_Comment: ''
  B100:
    R1: 210519_NB501038_0285_AHC3THBGXJ/GCF-2020-746/B100_R1.fastq.gz
    R2: 210519_NB501038_0285_AHC3THBGXJ/GCF-2020-746/B100_R2.fastq.gz
    paired_end: 1
    Sample_ID: B100
    External_ID: ''
    Project_ID: GCF-2020-746
    Organism: Human
    Sample_Biosource: Whole blood
    Index1_p7 (If dual indexed libraries are submitted indicate what index sequence is used P7): 710
    Index2_p5 (If libraries are submitted  indicate what index sequence is used P75): 503
    Sample_Group: ''
    Customer_Comment: ''
    Project ID: GCF-2020-746
    RIN: ''
    SpikeIn: ''
    Fragment_Length: ''
    Fragment_SD: ''
    Concentration: ''
    260/280: ''
    260/230: ''
    Lab_Comment: ''
