# This workflow will install snakemake==7.15.2 and test rule bfq_all

name: Test wgs

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install snakemake==8.1.1 pyyaml==6.0 peppy rich pulp==2.7.0
        python --version
    - name: Dry run bfq_all
      working-directory: ./wgs/.tests
      run: |
        snakemake -n -p --cores 1 multiqc_report
