# This workflow will install snakemake==7.7.0 and test rule bfq_all

name: Test microbiome

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9.5']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install snakemake==7.15.2 pyyaml==6.0 peppy==0.35.2 rich==12.6.0
        python --version
        python --version
    - name: Dry run bfq_all
      working-directory: ./microbiome/.tests
      run: |
        snakemake -n -p -j1 bfq_all
