$schema: "http://json-schema.org/draft-07/schema#"
min_len:
    type: int
    description: "minimum read length to retain"
min_qual:
    type: int
    description: "minimum quality score to retain"
scheme_bed:
    type: string
    description: "path to .bed file defining amplicon primer scheme"
viral_reference_genome:
    type: string
    description: "path to reference fasta for QC, removing non SARS-CoV2 sequences and generating consensus/variants"
viral_reference_feature_coords: 
    type: string
    description: "path to feature coords on reference viral genome for QC"
breseq_reference:
    type: string
    description: "path to enhanced reference gbk with clinical sequences"
kraken2_db:
    type: string
    description: "path to kraken2 database files"
mpileup_depth:
    type: int
    default: 100000
    description: "mpileup depth to use for ivar/samtools consensus and variant calling"
ivar_freq_threshold:
    type: float
    default: 0.75
    description: "ivar frequency threshold to build consensus"
ivar_min_coverage_depth:
    type: int
    default: 10
    description: "minimum coverage depth to call variant"
ivar_min_freq_threshold:
    type: float
    default: 0.25
    description: "ivar frequency threshold to call variant (ivar variants: -t )"
ivar_min_variant_quality:
    type: int
    default: 20
    description: "iVar minimum mapQ to call variant (ivar variants: -q)"
samples:
    type: string
    description: "Sample filepaths/table"
result_dir:
    type: string
    default: "results"
    description: "Path to output results"
required:
    - min_len
    - min_qual
    - scheme_bed
    - viral_reference_genome
    - viral_reference_feature_coords
    - breseq_reference
    - kraken2_db
    - samples
    - result_dir
